### ISSUE TITLE
winmm.dll causes the game to crash, error message says that the files MSVCP140D.dll, VCRUNTIME140D.dll & ucrtbased.dll are missing, despite having all Visual runtimes installed on my OS.

### ISSUE THREAD

**Issue by Hyperyia** [SuiMachine/Soldier-of-Fortune-2-SuisFix#1]
OS: Windows 10 Enterprise LTSC 2019 x64 (build: 1809, 17763.740)

Error message:

![image](https://user-images.githubusercontent.com/32967354/65516486-5feebc80-dee1-11e9-91d7-2df25b7f2c70.png)

I am aware that those errors are caused by visual runtimes missing, however i have all of them installed and it shouldn't be an issue and since 2019 are binary compatible with both 2015 and 2017 - maybe winmm.dll can't detect 2019 ones for some reason?

![image](https://user-images.githubusercontent.com/32967354/65516626-9e847700-dee1-11e9-9553-80e1205d421e.png)

**Comment by SuiMachine** [comment]
Oh. It's just debug libraries. Apparently when I switched to x86 build, Visual Studio copied over a profile from Debug, which uses libraries with D at the the end.

**Comment by SuiMachine** [comment]
https://github.com/SuiMachine/Soldier-of-Fortune-2-SuisFix/releases/tag/0.6.1 - this should fix it. Thanks for letting me know.

**Comment by Hyperyia** [comment]
Thanks, everything's working fine now.
